import os
import re
import fitz  # PyMuPDF engine to convert PDF vector grids into visual images
from PIL import Image
import customtkinter as ctk

class ResumeTab(ctk.CTkFrame):
    """
    Advanced layout module splitting the ATS Review window into a left-side
    scrollable PDF canvas reader and a right-side interactive suggestion card index.
    """
    def __init__(self, master):
        super().__init__(master)

        # Configure parent coordinate weights for split screen distribution
        self.grid_columnconfigure(0, weight=3) # PDF Viewer pane takes majority space
        self.grid_columnconfigure(1, weight=2) # Suggestion sidebar pane
        self.grid_rowconfigure(0, weight=1)

        # Container tracking array to keep track of loaded images in memory
        self.pdf_images = []

        # Left Column: Scrollable document frame simulating a standard PDF viewer
        self.pdf_viewer_frame = ctk.CTkScrollableFrame(self, label_text="Original Document View")
        self.pdf_viewer_frame.grid(row=0, column=0, padx=10, pady=10, sticky="nsew")

        # Right Column: Scrollable panel containing Grammarly-style alert cards
        self.sidebar_frame = ctk.CTkScrollableFrame(self, label_text="ATS Keyword & Optimization Rules")
        self.sidebar_frame.grid(row=0, column=1, padx=10, pady=10, sticky="nsew")

    def display_pdf_layout(self, pdf_path):
        """
        Renders the individual pages of the uploaded document into high-resolution
        Tkinter labels to enable native vertical scrolling.
        """
        # Clear any previous layout definitions
        for widget in self.pdf_viewer_frame.winfo_children():
            widget.destroy()
        self.pdf_images.clear()

        if not os.path.exists(pdf_path):
            return

        # Open the target document via the binary stream engine
        doc = fitz.open(pdf_path)
        for page_num in range(len(doc)):
            page = doc.load_page(page_num)
            
            # Render page to an image map using a scale factor for crisp text resolution
            pix = page.get_pixmap(matrix=fitz.Matrix(1.5, 1.5))
            img_data = pix.tobytes("ppm")
            
            # Unpack image data bytes into standard PIL structures
            pil_img = Image.open(fitz.io.BytesIO(img_data))
            ctk_img = ctk.CTkImage(light_image=pil_img, dark_image=pil_img, size=(550, 750))
            
            # Keep object handle reference alive in memory array
            self.pdf_images.append(ctk_img)

            # Draw the page inside the vertical UI layout frame
            lbl_page = ctk.CTkLabel(self.pdf_viewer_frame, image=ctk_img, text="")
            lbl_page.pack(padx=10, pady=15)

    def load_completed_file(self):
        """
        Parses the structured tokens out of the optimization agent output text,
        instantiating yellow-accented visual cards inside the sidebar pane.
        """
        # Clear out old suggestion cards from previous execution passes
        for widget in self.sidebar_frame.winfo_children():
            widget.destroy()

        target_file = "ats_optimized_resume.md"
        if not os.path.exists(target_file):
            return

        with open(target_file, "r", encoding="utf-8") as f:
            raw_content = f.read()

        # Regular expression rules to capture structural tokens generated by our task criteria
        suggestion_blocks = re.findall(r'START_SUGGESTION(.*?)END_SUGGESTION', raw_content, re.DOTALL)

        if not suggestion_blocks:
            # Fallback wrapper if the model output data lacks parsable tokens
            lbl_fallback = ctk.CTkLabel(
                self.sidebar_frame, 
                text="No structured suggestions found.\nReview raw playbook records for details.",
                text_color="gray"
            )
            lbl_fallback.pack(padx=20, pady=20)
            return

        # Sequentially loop through parsed blocks to construct layout frames
        for block in suggestion_blocks:
            # Isolate attribute strings via regular expression matching
            section_match = re.search(r'SECTION:\s*(.*?)(?=\n\s*ISSUE:|\n\s*CORRECTION:|$)', block, re.IGNORECASE)
            issue_match = re.search(r'ISSUE:\s*(.*?)(?=\n\s*SECTION:|\n\s*CORRECTION:|$)', block, re.IGNORECASE)
            correction_match = re.search(r'CORRECTION:\s*(.*?)(?=\n\s*SECTION:|\n\s*ISSUE:|$)', block, re.IGNORECASE)

            section_text = section_match.group(1).strip() if section_match else "General Setup"
            issue_text = issue_match.group(1).strip() if issue_match else "Optimization Alert"
            correction_text = correction_match.group(1).strip() if correction_match else block.strip()

            # Construct the yellow accented card frame object
            card = ctk.CTkFrame(self.sidebar_frame, border_width=2, border_color="#FFCC00", corner_radius=8)
            card.pack(fill="x", padx=10, pady=10)

            # Section Header Tag Label
            lbl_sec = ctk.CTkLabel(card, text=section_text.upper(), font=ctk.CTkFont(size=10, weight="bold"), text_color="#FFCC00")
            lbl_sec.pack(anchor="w", padx=12, pady=(8, 2))

            # Core Issue Description Label
            lbl_iss = ctk.CTkLabel(card, text=issue_text, font=ctk.CTkFont(size=14, weight="bold"), wraplength=320, justify="left")
            lbl_iss.pack(anchor="w", padx=12, pady=2)

            # Explanatory Text Bubble/Body Box
            lbl_cor = ctk.CTkLabel(card, text=correction_text, font=ctk.CTkFont(size=12), wraplength=320, justify="left", text_color="light gray")
            lbl_cor.pack(anchor="w", padx=12, pady=(4, 10))